<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTuMAXhB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTuMAXhB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTuMAXhB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTuMAXhB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTuMAXhB\App_KernelDevDebugContainer([
    'container.build_hash' => 'TuMAXhB',
    'container.build_id' => '770f429d',
    'container.build_time' => 1629165412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTuMAXhB');
