<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBDZfBEo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBDZfBEo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBDZfBEo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBDZfBEo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBDZfBEo\App_KernelDevDebugContainer([
    'container.build_hash' => 'BDZfBEo',
    'container.build_id' => 'f5db4637',
    'container.build_time' => 1629163705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBDZfBEo');
